name: deployment of code
on: push
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: get code
        run: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: lint
        run: npm run lint
      - name: test code
        run: npm test
      - name: Build code
        run: npm build
      - name: Deploy code
        run: echo "deploy code"
